# Blatt 3

Auf Blatt 1 hattest du bereits gelernt, wie man Vektoren mit numpy erstellen kann. Ebenso kannst du auch Matrizen als numpy Objekt erstellen. Zuerst importieren wir hierfür wieder numpy:

In [1]:
import numpy as np

In [2]:
b = np.array([3, 4, 1])
A = np.array([[6, -1, 3], [7, -2, -2], [-5, 2, 4]])

### Matrix-Vektor Multiplikation

In [11]:
A*b

array([[ 18,  -4,   3],
       [ 21,  -8,  -2],
       [-15,   8,   4]])

In [12]:
np.matmul(A, b)

array([17, 11, -3])

### Lineare Gleichungssysteme

Verwende np.linalg.solve

In [4]:
np.linalg.solve(A, b)

array([ 6. , 22.5, -3.5])

np.linalg.solve kann nur für eindeutig lösbare LGS verwendet werden:

In [5]:
B = np.array([[-6, 9, -12], [2, -3, 4], [4, -6, 8]])
c = np.array([-20, 7, 12])

In [6]:
np.linalg.solve(B, c)

LinAlgError: Singular matrix

In [7]:
d = np.array([0, 0, 0])

In [8]:
np.linalg.solve(B, d)

LinAlgError: Singular matrix

In [9]:
np.linalg.lstsq(B, c)

(array([ 0.44827586, -0.67241379,  0.89655172]),
 array([], dtype=float64),
 np.int32(1),
 array([2.01494417e+01, 1.80672411e-15, 8.85640569e-32]))

In [10]:
np.linalg.lstsq(B, d)

(array([0., 0., 0.]),
 array([], dtype=float64),
 np.int32(1),
 array([2.01494417e+01, 1.80672411e-15, 8.85640569e-32]))

Returns least square solution, residuals, rank of matrix, singular values of matrix