# Blatt 3

Auf Blatt 1 hattest du bereits gelernt, wie man Vektoren mit numpy erstellen kann. Ebenso kannst du auch Matrizen als numpy Objekt erstellen. Zuerst importieren wir hierfür wieder numpy:

In [1]:
import numpy as np

Nun erstellen wir den Vektor $b$ und die Matrix $A$. Wie man einen `numpy`-Vektor erstellt weißt du bereits. Um eine `numpy`-Matrix zu erstellen verwenden wir eine Liste, die mehrere Listen enthält. Diese Listen repräsentieren dabei die *Zeilen* der Matrix. 

In [2]:
b = np.array([3, 4, 1])
A = np.array([[6, -1, 3], [7, -2, -2], [-5, 2, 4]])

print('b:', b)
print('A:', A)

b: [3 4 1]
A: [[ 6 -1  3]
 [ 7 -2 -2]
 [-5  2  4]]


Damit A auch als Matrix eingelesen werden kann, muss jede Liste gleich viele Zahlen beinhalten. Ist dies nicht der Fall, erhalten wir folgende Fehlermeldung:

In [3]:
A = np.array([[3,4], [2,5,3], [8,3,5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

### Matrix-Vektor Multiplikation

Im folgenden möchten wir das Produkt der Matrix $A$ mit dem Vektor $b$ berechnen. Intuitiv könnte man hier `A*b` ausrechnen. Dieser Befehl liefert auch ein Ergebnis, jedoch entspricht das nicht dem Matrix-Vektor-Produkt! Wenn du in Python mit NumPy arbeitest, führt der Ausdruck A * b eine elementweise Multiplikation durch (auch bekannt als Element-wise Multiplication oder Hadamard-Produkt).

Das Ergebnis ist eine Matrix derselben Form wie $A$, bei der jedes Element $a_{ij}$ mit dem entsprechenden Element $b_j$ multipliziert wurde.

In [11]:
A*b

array([[ 18,  -4,   3],
       [ 21,  -8,  -2],
       [-15,   8,   4]])

Um die Matrix-Vektor-Multiplikation richtig durchzuführen haben wir verschiedene Möglichkeiten:

In [4]:
c = A @ b
d = np.matmul(A, b)
e = np.dot(A,b)

print(c, d, e)

[17 11 -3] [17 11 -3] [17 11 -3]


### Lineare Gleichungssysteme

Wir können mit `numpy` aus LGS der Form $A \cdot x = b$ lösen. Hierfür wird der Befehl `np.linalg.solve()` verwendet.

In [7]:
x = np.linalg.solve(A, b)

print('x:', x)

# Zur Überprüfung
print('A@x:', A@x)
print('b:', b)

x: [ 6.  22.5 -3.5]
A@x: [3. 4. 1.]
b: [3 4 1]


`np.linalg.solve()` kann nur für eindeutig lösbare LGS verwendet werden:

In [9]:
B = np.array([[-6, 9, -12], [2, -3, 4], [4, -6, 8]])
c = np.array([-20, 7, 12])

np.linalg.solve(B,c)

LinAlgError: Singular matrix

### TBD: Eigenwerte, Eigenvektoren mit numpy berechnen

In [ ]:
import numpy as np

In [ ]:
B = np.array([[1, -2], [3, -4]])

In [ ]:
eigenwerte, eigenvektoren = np.linalg.eig(B)
l1, l2 = eigenwerte
v1, v2 = eigenvektoren[:, 0], eigenvektoren[:, 1]

In [ ]:
w1 = np.matmul(B, v1)
w2 = np.matmul(B, v2)